// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Repositorio.DataAccess;

#nullable disable

namespace Repositorio.Migrations
{
    [DbContext(typeof(WorldCupPlannerDbContext))]
    [Migration("20260614190009_AgregarFixtureGrupoJornada")]
    partial class AgregarFixtureGrupoJornada
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Dominio.Equipo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BanderaBase64")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Confederacion")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<int>("RankingActual")
                        .HasColumnType("int");

                    b.Property<int>("RankingFIFA")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("Equipos", (string)null);
                });

            modelBuilder.Entity("Dominio.Estadio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Capacidad")
                        .HasColumnType("int");

                    b.Property<string>("Ciudad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Estadios");
                });

            modelBuilder.Entity("Dominio.Fixture", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("CrucesGenerados")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaGeneracion")
                        .HasColumnType("datetime2");

                    b.Property<string>("NombreMotorSimulacion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("SemillaUtilizada")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Fixtures", (string)null);
                });

            modelBuilder.Entity("Dominio.Grupo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Etiqueta")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<int?>("FixtureId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FixtureId");

                    b.ToTable("Grupos", (string)null);
                });

            modelBuilder.Entity("Dominio.Incidencia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("EsLocal")
                        .HasColumnType("bit");

                    b.Property<int>("MinutoJuego")
                        .HasColumnType("int");

                    b.Property<int?>("PartidoId")
                        .HasColumnType("int");

                    b.Property<int?>("PartidoId1")
                        .HasColumnType("int");

                    b.Property<int?>("PartidoId2")
                        .HasColumnType("int");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("nvarchar(21)");

                    b.HasKey("Id");

                    b.HasIndex("PartidoId");

                    b.HasIndex("PartidoId1");

                    b.HasIndex("PartidoId2");

                    b.ToTable("Incidencias", (string)null);

                    b.HasDiscriminator<string>("Tipo").HasValue("Incidencia");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Dominio.Jornada", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<int?>("GrupoId")
                        .HasColumnType("int");

                    b.Property<int>("Numero")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("GrupoId");

                    b.ToTable("Jornadas", (string)null);
                });

            modelBuilder.Entity("Dominio.LogEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Accion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Detalle")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.Property<string>("UsuarioEmail")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("Logs", (string)null);
                });

            modelBuilder.Entity("Dominio.Notificacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Leida")
                        .HasColumnType("bit");

                    b.Property<string>("Mensaje")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("PartidoId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Notificaciones", (string)null);
                });

            modelBuilder.Entity("Dominio.Partido", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EquipoLocalId")
                        .HasColumnType("int");

                    b.Property<int>("EquipoVisitanteId")
                        .HasColumnType("int");

                    b.Property<int>("EstadioId")
                        .HasColumnType("int");

                    b.Property<string>("EtiquetaCruce")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Fase")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<int?>("FixtureEliminatoriasId")
                        .HasColumnType("int");

                    b.Property<int?>("GolesLocal")
                        .HasColumnType("int");

                    b.Property<int?>("GolesPenalesLocal")
                        .HasColumnType("int");

                    b.Property<int?>("GolesPenalesVisitante")
                        .HasColumnType("int");

                    b.Property<int?>("GolesVisitante")
                        .HasColumnType("int");

                    b.Property<string>("Grupo")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<int?>("JornadaId")
                        .HasColumnType("int");

                    b.Property<int?>("PartidoOrigenLocalId")
                        .HasColumnType("int");

                    b.Property<int?>("PartidoOrigenVisitanteId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EquipoLocalId");

                    b.HasIndex("EquipoVisitanteId");

                    b.HasIndex("EstadioId");

                    b.HasIndex("FixtureEliminatoriasId");

                    b.HasIndex("JornadaId");

                    b.HasIndex("PartidoOrigenLocalId");

                    b.HasIndex("PartidoOrigenVisitanteId");

                    b.ToTable("Partidos", (string)null);
                });

            modelBuilder.Entity("Dominio.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("CorreoElectronico")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateOnly>("FechaNacimiento")
                        .HasColumnType("date");

                    b.Property<string>("HashDeContrasena")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("CorreoElectronico")
                        .IsUnique();

                    b.ToTable("Usuarios", (string)null);
                });

            modelBuilder.Entity("EquipoGrupo", b =>
                {
                    b.Property<int>("EquiposId")
                        .HasColumnType("int");

                    b.Property<int>("GrupoId")
                        .HasColumnType("int");

                    b.HasKey("EquiposId", "GrupoId");

                    b.HasIndex("GrupoId");

                    b.ToTable("GrupoEquipos", (string)null);
                });

            modelBuilder.Entity("Repositorio.UsuarioRolRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("UsuarioRoles", (string)null);
                });

            modelBuilder.Entity("Dominio.TarjetaAmarilla", b =>
                {
                    b.HasBaseType("Dominio.Incidencia");

                    b.HasDiscriminator().HasValue("TarjetaAmarilla");
                });

            modelBuilder.Entity("Dominio.TarjetaRoja", b =>
                {
                    b.HasBaseType("Dominio.Incidencia");

                    b.HasDiscriminator().HasValue("TarjetaRoja");
                });

            modelBuilder.Entity("Dominio.Grupo", b =>
                {
                    b.HasOne("Dominio.Fixture", null)
                        .WithMany("Grupos")
                        .HasForeignKey("FixtureId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Dominio.Incidencia", b =>
                {
                    b.HasOne("Dominio.Partido", null)
                        .WithMany("Incidencias")
                        .HasForeignKey("PartidoId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Dominio.Partido", null)
                        .WithMany("IncidenciasLocal")
                        .HasForeignKey("PartidoId1");

                    b.HasOne("Dominio.Partido", null)
                        .WithMany("IncidenciasVisitante")
                        .HasForeignKey("PartidoId2");
                });

            modelBuilder.Entity("Dominio.Jornada", b =>
                {
                    b.HasOne("Dominio.Grupo", null)
                        .WithMany("Jornadas")
                        .HasForeignKey("GrupoId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Dominio.Partido", b =>
                {
                    b.HasOne("Dominio.Equipo", "EquipoLocal")
                        .WithMany()
                        .HasForeignKey("EquipoLocalId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Dominio.Equipo", "EquipoVisitante")
                        .WithMany()
                        .HasForeignKey("EquipoVisitanteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Dominio.Estadio", "Estadio")
                        .WithMany()
                        .HasForeignKey("EstadioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Dominio.Fixture", null)
                        .WithMany("PartidosEliminatorias")
                        .HasForeignKey("FixtureEliminatoriasId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Dominio.Jornada", null)
                        .WithMany("Partidos")
                        .HasForeignKey("JornadaId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Dominio.Partido", "PartidoOrigenLocal")
                        .WithMany()
                        .HasForeignKey("PartidoOrigenLocalId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Dominio.Partido", "PartidoOrigenVisitante")
                        .WithMany()
                        .HasForeignKey("PartidoOrigenVisitanteId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("EquipoLocal");

                    b.Navigation("EquipoVisitante");

                    b.Navigation("Estadio");

                    b.Navigation("PartidoOrigenLocal");

                    b.Navigation("PartidoOrigenVisitante");
                });

            modelBuilder.Entity("EquipoGrupo", b =>
                {
                    b.HasOne("Dominio.Equipo", null)
                        .WithMany()
                        .HasForeignKey("EquiposId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Dominio.Grupo", null)
                        .WithMany()
                        .HasForeignKey("GrupoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Repositorio.UsuarioRolRecord", b =>
                {
                    b.HasOne("Dominio.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Dominio.Fixture", b =>
                {
                    b.Navigation("Grupos");

                    b.Navigation("PartidosEliminatorias");
                });

            modelBuilder.Entity("Dominio.Grupo", b =>
                {
                    b.Navigation("Jornadas");
                });

            modelBuilder.Entity("Dominio.Jornada", b =>
                {
                    b.Navigation("Partidos");
                });

            modelBuilder.Entity("Dominio.Partido", b =>
                {
                    b.Navigation("Incidencias");

                    b.Navigation("IncidenciasLocal");

                    b.Navigation("IncidenciasVisitante");
                });
#pragma warning restore 612, 618
        }
    }
}
